name: ayon-aquarium-services
services:
  leecher:
    container_name: leecher
    image: ghcr.io/fatfish-lab/ayon-aquarium-leecher:0.0.4
    restart: unless-stopped
    environment:
      - "AYON_SERVER_URL=${AYON_SERVER_URL}"
      - "AYON_API_KEY=${AYON_API_KEY}"
      - "AYON_ADDON_NAME=aquarium"
      - "AYON_ADDON_VERSION=0.0.4"
